name: snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   # ✅ updated

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: subhrajitsahoo72-in
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Deploy to branch
        uses: peaceiris/actions-gh-pages@v4   # ✅ updated
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
